### ISSUE TITLE
Add Dependabot to Update Dependencies

### ISSUE THREAD

**Issue by nelsonic** [dwyl/envar#10]
Just spotted another `Elixir` project that doesn't have auto-dependency updates. 
Not really a problem in the case of _this_ repo where we have no actual depenencies only `:dev` and `:test` ...
https://github.com/dwyl/envar/blob/5d5291d854d79d4f2cd346d8c63b2dfaf74878d1/mix.exs#L33-L44

But just for completeness and to delegate updating to 🤖  ...

# Todo:

+ [ ] Create a file with the following path: `.github/dependabot.yml`

With the following contents:
```
version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
```

Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

see: https://github.com/dwyl/fields/tree/main/.github
